project:
  name: simulation
  subject: Apollo
  # data_root_folder: /Users/yoon/raw_data/ # this is the root folder where all the raw data resides for the pipeline
  nwb_output_folder: /Users/yoon/Downloads/simulation/nwb_files
  project_version: 1.0
  pipeline_version: EVPP_1.0 # Extracellular Voltage Preprocessing Pipeline version 
  code_version: 3.1
  mworks_version: 0.13
  experiments: # list day(s) of experiment(s)
    - date: 20240924
      sessions: # ... and individual session(s) per day in chronological order
        - stimulus_name: normalizers.V3
          stimulus_folder: /Users/yoon/Dropbox (MIT)/dorsal_ventral/pipeline_lab/stimuli/RSVP-normalizers-v3/images
          mworks_folder: /Users/yoon/raw_data/Apollo/MonkeyValence/20240924/normalizers_240924_123021
          data_folder: /Users/yoon/raw_data/Apollo/MonkeyValence/20240924/normalizers_240924_123021
          psth_start_s: -0.200 # relative to stimulus onset at 0s
          psth_end_s: 0.300 # relative to stimulus onset at 0s, e.g., 100ms stimulus duration + 200ms post-stimulus
          psth_bin_size_s: 0.010 # 10 ms
          notes: none # in case there were any noteworthy events that happened during the experiment
        - stimulus_name: simulation
          stimulus_folder: /Users/yoon/Dropbox (MIT)/dorsal_ventral/pipeline_lab/stimuli/RSVP-normalizers-v3/images
          mworks_folder: /Users/yoon/raw_data/Apollo/simulation_240924_131313
          data_folder: /Users/yoon/raw_data/Apollo/simulation_240924_131313
          psth_start_s: -0.200 # relative to stimulus onset at 0s
          psth_end_s: 0.500 # relative to stimulus onset at 0s
          psth_bin_size_s: 0.010 # 10 ms
          notes: n/a
        
    # date: 20240925